### ISSUE TITLE
Issue updating some containers in latest version

### ISSUE THREAD

**Issue by marmata** [mag37/dockcheck#173]
Hi all,

I've an issue with the latest version of dockcheck. Some containers do not update with a network error, which stops subsequent updates for the other containers as well. Happening on multiple hosts, and everything was working before version was updated (talking about v0.6.3). Here is what happens:

```
Updating container(s):
adguardhome
dozzle
jelu
meshcentral
miniflux-db-1
paperless-broker-1
prowlarr


Now updating (1/7): adguardhome
Using default tag: latest
latest: Pulling from adguard/adguardhome
Digest: sha256:a2085b04bbfc4759e68fa1d13d4e1558aede67c783c55820e036a95a36dd3ebf
Status: Image is up to date for adguard/adguardhome:latest
docker.io/adguard/adguardhome:latest
WARN[0000] /home/marmata/adguard/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
WARN[0000] a network with name adguard_default exists but was not created by compose.
Set `external: true` to use an existing network
network adguard_default was found but has incorrect label com.docker.compose.network set to "" (expected: "default")

Docker error, exiting!

```

So I see two issues:
* The container is set to be updates, but the image is deemed to be updated already
* The last line I think is the blocker, and looks like an error from the underlying docker command, but why was not happening before?

For reference the docker compose of that particular container:

```
$ cat docker-compose.yml
version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 3001:3001/tcp
      - 853:853/tcp
      - 784:784/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped

```

I tried to prune the docker network to no avail (all the networks are used). Also tried to revert back to 0.6.2 and all working fine again so doesn't seem to be a specific docker damon issue, but more something that changed within dockcheck?

Thanks for your help!

**Comment by mag37** [comment]
>WARN[0000] /home/marmata/adguard/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

This first warning is solved by just removing the deprecated `version:` line in the compose-file.

>WARN[0000] a network with name adguard_default exists but was not created by compose.

The only thing that changed that might affect this is the removal of the container name specification:
```
## v0.6.2 (thenline 520):
        ${DockerBin} ${CompleteConfs} ${ContEnvs} up -d ${ContName}`
## v0.6.3 (now line 537):
        ${DockerBin} ${CompleteConfs} ${ContEnvs} up -d || { printf "\n%bDocker error, exiting!%b\n" "$c_red" "$c_reset" ; exit 1; }
```
As you might see - the variable ` ${ContName}` was removed - hence it will ensure the whole stack (if depending on) is started/restarted if needed, not just the specific container.


Good to know that it can cause issue, thank you for reporting and pasting output! 
I need to revisit this and do some testing then.  

But the issue might be something underlying/solvable outside of `dockcheck.sh`. 
The `adguard_default` network might be created prior to running the container, either manually or by a custom setup script or if you started out with a `docker run` command before you made the compose etc.  
What if you stop the container, then do `docker network rm adguard_default` and then start it as usual with `docker compose ...` again?

**Comment by iamtherobin** [comment]
Update your compose file to the following see if the issue goes away:
```
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp
      - 3001:3001/tcp
      - 853:853/tcp
      - 784:784/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      - adguardhome

networks:
  adguardhome:
    name: adguard_default
    external: true
```
